name: Publicación Automática

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Compilando para iOS y macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos

      - name: Build iOS (sin firma)
        run: flutter build ios --no-codesign

      - name: Comprimir ejecutables
        run: |
          cd build/macos/Build/Products/Release
          zip -r myapp-macOS.app.zip myapp.app

          cd ../../../../ios/iphoneos
          zip -r myapp-iOS.app.zip Runner.app

      - name: Crear Release y subir archivos
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/macos/Build/Products/Release/myapp-macOS.app.zip
            build/ios/iphoneos/myapp-iOS.app.zip
